backend:
  name: github
  branch: master
  repo: olavea/3.8Ronny_Rev_og_Geir_Grevling

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Image", name: "title", widget: "Image" }

